"""v3

Revision ID: 05d9a0008657
Revises: 692bd2dd7529
Create Date: 2024-10-28 18:32:58.892267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05d9a0008657'
down_revision: Union[str, None] = '692bd2dd7529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password')
    op.drop_table('operation')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    op.drop_column('user', 'hashed_password')
    op.create_table('password',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], name='password_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_pkey')
    )
    # ### end Alembic commands ###
