"""v2

Revision ID: 692bd2dd7529
Revises: c3b8f72e9370
Create Date: 2024-10-27 19:24:36.058066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '692bd2dd7529'
down_revision: Union[str, None] = 'c3b8f72e9370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', postgresql.BYTEA(), nullable=False),
    sa.Column('salt', postgresql.BYTEA(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_table('password')
    # ### end Alembic commands ###
