#name: Build docker image and test
#
#on:
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build_and_push_to_docker_hub:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Build
#        run: docker build .
